# Change these first
owner: FanboyStudios # Your GitHub organization or username, where this repository lives
repo: RFMG-Status-Monitor # The name of this repository

sites:
  - name: Random Fandom
    url: https://rfmg.top
  - name: Random Fandom Forum
    url: https://forum.rfmg.top
  - name: Random Fandom Profiles
    url: https://rfmg.top/RFMG
  - name: Random Fandom Shop
    url: https://shop.rfmg.top
  - name: RFMG Search
    url: http://search.rfmg.top:8880
  - name: The Advertiser Creators Consumers Association
    url: https://acca.rfmg.top
  - name: The No Pay To Win Coalition
    url: https://nop2wc.rfmg.top
  - name: RCERC
    url: https://rcerc.org
  - name: RCERC Forum
    url: https://forum.rcerc.org
  - name: WBC
    url: https://wadleybaptistchurch.cf
    
assignees: # Users to assign downtime issues (optional)
  - FanboyStudios

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /RFMG-Status-Monitor
  cname: status.rfmg.top
  theme: ocean
  logoUrl: https://raw.githubusercontent.com/FanboyStudios/RFMG-Status-Monitor/master/assets/Random%20Fandom%20Logo%20-%20Round.svg
  name: Random Fandom Media Group
  introTitle: "**Random Fandom Media Group - Status Monitor**"
  introMessage: This status page lists services maintained by Random Fandom Media Group, as well as client services. (I might phase out this status monitor, as it is not working properly anymore. Some sites that currently show as being down are actually working fine.)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
